In [1]:
import numpy as np
import pickle
import pandas as pd

In [2]:
with open('vectors.pkl', 'rb') as f:
    vectors = pickle.load(f)

In [3]:
len(vectors)

30

In [4]:
x = vectors[0]

In [5]:
parameters = []
for x in vectors:
    temp = 0
    for i in range(x.T.shape[0]):
        temp += x.T[i]
    temp= temp/ x.T.shape[0]
    param = np.append(temp,np.std(x.T, axis=0))
    parameters.append(param)

In [6]:
parameters

[array([-0.02436643,  0.00428667,  0.03342887, ...,  0.21807387,
         0.71923834,  0.66237533], dtype=float32),
 array([-0.05004442,  0.08577038, -0.15335314, ...,  0.5457179 ,
         0.53994834,  0.5186221 ], dtype=float32),
 array([-0.0478214 ,  0.06822757,  0.03541551, ...,  0.64311576,
         0.55215675,  0.55968946], dtype=float32),
 array([ 0.02299708, -0.04792721,  0.0820884 , ...,  0.9557422 ,
         0.95049196,  0.95530057], dtype=float32),
 array([-0.00388455,  0.11227497, -0.04985452, ...,  0.6616517 ,
         0.6988491 ,  0.66887283], dtype=float32),
 array([-0.0271099 , -0.05291145,  0.02450637, ...,  0.6919318 ,
         0.7214049 ,  0.74052006], dtype=float32),
 array([ 0.01384578, -0.12987998, -0.03196469, ...,  0.7052927 ,
         0.7132905 ,  0.70332366], dtype=float32),
 array([ 0.03572064, -0.05694216, -0.09738419, ...,  0.9854146 ,
         0.98779607,  0.9915016 ], dtype=float32),
 array([0.0687818 , 0.04995634, 0.08529423, ..., 0.9823067 , 0.9857036 ,

In [9]:
vectors[0].T.shape

(20, 2672)